# -*- coding: utf-8 -*-
"""For while loops.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AhXqAdIYgvW3INxgblyveSpXc2LAakND
"""

i = 1
#result = 1
while(i<=100):
      #result = result *i
      if i ==42:
         print('Magic number reached 42, stop execution')
         break
      i = i+1

i = 1
result = 1
while i<=10:
  i = i+1
  if i % 2 ==0:
    print('divisible by {}'.format(i))
    continue
  print('inside if, after continue')
  print('Not divisible {}'.format(i))
  result = result*i

print('i:',i)
print('result:',result)

days = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
for day in days:
  print(day)

#for value in sequence:
 # statement()

# looping over a string
for char in 'Monday':
  print(char)

#looping over a tuple
cars = ('toyota', 'BMW', 'Honda')
for vehicle in cars:
  print("machines:",vehicle)

#looping over a dictionary
pallets = {
           'length': '1.0m',
           'width': '0.6m',
           'height': '1.2m',
           'heavy': False
}
for dims in pallets:
    print(dims, pallets[dims])

pallets = {
           'length': '1.0m',
           'width': '0.6m',
           'height': '1.2m',
           'heavy': False
}
for value in pallets.values():
    print(value)

for dim_value_pair in pallets.items():
    print(dim_value_pair)

for dim, value in pallets.items():
    print('dim:',dim,'value:',value)

"""### Iterating using `range` and `enumerate`

The `range` function is used to create a sequence of numbers that can be iterated over using a `for` loop. It can be used in 3 ways:

* `range(n)` - Creates a sequence of numbers from `0` to `n-1`
* `range(a, b)` - Creates a sequence of numbers from `a` to `b-1`
* `range(a, b, step)` - Creates a sequence of numbers from `a` to `b-1` with increments of `step`
"""

for i in range(7):
    print (i)

for i in range(3,12):
    print(i)

for i in range (3,12,2):
    print (i)

vehicles_list = ['Toyota', 'Honda', 'BMW', 'Volkswagon', 'Mazda', 'Ford', 'Porshe']
for i in range(len(vehicles_list)):
    print('the value of {} is {}'.format(i,vehicles_list[i]))

for i, val in enumerate(vehicles_list):
    print('the value in {} is {}'.format(i,val))

weekday = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday']
for day in weekday:
    print('today is {}'. format(day))

weekday = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday']
for day in weekday:
    print('today is {}'.format(day))
    if (day =='Thursday'):
        print('Work from home')
        break

weekday = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday']
for day in weekday:
    print('today is {}'. format(day))
    if(day == 'Thursday'):
       print('work from home')
       continue
    #print('today is {}'.format(day))

pets = [{'name': 'cooper', 'age': '10'}, {'name': 'pon', 'age': '14'}]
for dog in pets:
    for key in dog:
        print(key, dog[key])

